# Generated by Django 5.1.4 on 2025-02-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="verification_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=6,
                null=True,
                unique=True,
            ),
        ),
    ]
