# Generated by Django 5.1.4 on 2025-02-03 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverification_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 2, 3, 18, 23, 34, 754000, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
