# Generated by Django 5.1.4 on 2025-01-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_food_image_food_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
