# Generated by Django 5.1.4 on 2025-01-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0003_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="foods.food"
            ),
        ),
    ]
