# Generated by Django 5.1.4 on 2025-01-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_order_is_delivered_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="price",
            field=models.FloatField(default=99.9),
        ),
    ]
